// <auto-generated />
using System;
using AracGorevFormu.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AracGorevFormu.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("AracGorevFormu.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AnaYonetici")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers", (string)null);
                });

            modelBuilder.Entity("AracGorevFormu.Models.AracBakim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BakimTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("BakimTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Km")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Maliyet")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plaka")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServisAdi")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SonrakiBakimKm")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SonrakiBakimTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YapilanIslemler")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AracBakimlari", (string)null);
                });

            modelBuilder.Entity("AracGorevFormu.Models.ArventoAyari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ArventoAyarlari", (string)null);
                });

            modelBuilder.Entity("AracGorevFormu.Models.DosyaEki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DosyaAdi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DosyaTipi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Icerik")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YuklenmeTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DosyaEkleri", (string)null);
                });

            modelBuilder.Entity("AracGorevFormu.Models.GorevFormu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AracMarka")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AracModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AracPlaka")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CikisKm")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CikisZamani")
                        .HasColumnType("TEXT");

                    b.Property<string>("Departman")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DonusKm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Durum")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GercekDonusZamani")
                        .HasColumnType("TEXT");

                    b.Property<string>("GorevAmaci")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("KullananAdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("KullananTelefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("OnaylayanKullaniciAdi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlanlananDonusZamani")
                        .HasColumnType("TEXT");

                    b.Property<string>("RedNedeni")
                        .HasColumnType("TEXT");

                    b.Property<string>("TakipKodu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TakipKodu");

                    b.ToTable("GorevFormlari", (string)null);
                });

            modelBuilder.Entity("AracGorevFormu.Models.HgsGecis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CezaMi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GecisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("GiseAdı")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("OdediMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Plaka")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HgsGecisleri", (string)null);
                });

            modelBuilder.Entity("AracGorevFormu.Models.Makine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CalismaSaati")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lokasyon")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Marka")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriNo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Makineler", (string)null);
                });

            modelBuilder.Entity("AracGorevFormu.Models.MakineBakim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BakimTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("BakimTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BakimiYapan")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("CalismaSaati")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DegisenParcalar")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("MakbuzDosyaYolu")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("MakbuzMetni")
                        .HasColumnType("TEXT");

                    b.Property<int>("MakineId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Maliyet")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SonrakiBakimCalismaSaati")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SonrakiBakimTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("YapilanIslemler")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MakineId");

                    b.ToTable("MakineBakimlari", (string)null);
                });

            modelBuilder.Entity("AracGorevFormu.Models.SmtpAyari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableSsl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotificationEmails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpServer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SmtpAyarlari", (string)null);
                });

            modelBuilder.Entity("AracGorevFormu.Models.SystemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAdresi")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("IslemTuru")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SystemLogs", (string)null);
                });

            modelBuilder.Entity("AracGorevFormu.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GuncelKm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lokasyon")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MotorNo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MuayeneBitisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plaka")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Renk")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuhsatDosyaAdi")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RuhsatDosyaIcerigi")
                        .HasColumnType("BLOB");

                    b.Property<string>("RuhsatDosyaTipi")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuhsatDosyaYolu")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SabitSurucu")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SahiplikTuru")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("SasiNo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SigortaBitisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("SonAdres")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SonKonumZamani")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TescilTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Plaka");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("AracGorevFormu.Models.MakineBakim", b =>
                {
                    b.HasOne("AracGorevFormu.Models.Makine", "Makine")
                        .WithMany()
                        .HasForeignKey("MakineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Makine");
                });
#pragma warning restore 612, 618
        }
    }
}
